# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FluidicTools.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FludicsForm(object):
    def setupUi(self, FludicsForm):
        FludicsForm.setObjectName("FludicsForm")
        FludicsForm.resize(640, 480)
        self.Fluidiclabel = QtWidgets.QLabel(FludicsForm)
        self.Fluidiclabel.setGeometry(QtCore.QRect(150, 120, 201, 131))
        self.Fluidiclabel.setObjectName("Fluidiclabel")

        self.retranslateUi(FludicsForm)
        QtCore.QMetaObject.connectSlotsByName(FludicsForm)

    def retranslateUi(self, FludicsForm):
        _translate = QtCore.QCoreApplication.translate
        FludicsForm.setWindowTitle(_translate("FludicsForm", "Fluidic Tools"))
        self.Fluidiclabel.setText(_translate("FludicsForm", "暂不开放，敬请期待"))
