# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MetricsTools.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MetricsTools(object):
    def setupUi(self, MetricsTools):
        MetricsTools.setObjectName("MetricsTools")
        MetricsTools.resize(640, 480)
        self.widget = QtWidgets.QWidget(MetricsTools)
        self.widget.setGeometry(QtCore.QRect(204, 170, 191, 104))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.QcPushButton = QtWidgets.QPushButton(self.widget)
        self.QcPushButton.setObjectName("QcPushButton")
        self.verticalLayout.addWidget(self.QcPushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.FovpushButton = QtWidgets.QPushButton(self.widget)
        self.FovpushButton.setObjectName("FovpushButton")
        self.verticalLayout.addWidget(self.FovpushButton)

        self.retranslateUi(MetricsTools)
        QtCore.QMetaObject.connectSlotsByName(MetricsTools)

    def retranslateUi(self, MetricsTools):
        _translate = QtCore.QCoreApplication.translate
        MetricsTools.setWindowTitle(_translate("MetricsTools", "Metrics Tools"))
        self.QcPushButton.setText(_translate("MetricsTools", "QC Metrics"))
        self.FovpushButton.setText(_translate("MetricsTools", "FOV Metrics"))
