# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MGIEngineerAnalysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MGIMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 492)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(640, 436))
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(180, 100, 281, 201))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MetricsButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MetricsButton.setFont(font)
        self.MetricsButton.setObjectName("MetricsButton")
        self.verticalLayout.addWidget(self.MetricsButton)
        self.OpticsButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.OpticsButton.setFont(font)
        self.OpticsButton.setObjectName("OpticsButton")
        self.verticalLayout.addWidget(self.OpticsButton)
        self.FluidicButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FluidicButton.setFont(font)
        self.FluidicButton.setObjectName("FluidicButton")
        self.verticalLayout.addWidget(self.FluidicButton)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(20, 410, 592, 22))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Information_label = QtWidgets.QLabel(self.widget1)
        self.Information_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Information_label.setObjectName("Information_label")
        self.horizontalLayout.addWidget(self.Information_label)
        spacerItem = QtWidgets.QSpacerItem(398, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.version_label = QtWidgets.QLabel(self.widget1)
        self.version_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.version_label.setAlignment(QtCore.Qt.AlignCenter)
        self.version_label.setObjectName("version_label")
        self.horizontalLayout.addWidget(self.version_label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MGI Engineering Analysis"))
        self.MetricsButton.setText(_translate("MainWindow", "Metrics Tools"))
        self.OpticsButton.setText(_translate("MainWindow", "Optics Tools"))
        self.FluidicButton.setText(_translate("MainWindow", "Fluidic Tools"))
        self.Information_label.setText(_translate("MainWindow", "Author Information"))
        self.version_label.setText(_translate("MainWindow", "version 0.01"))
