# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpticsTools.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpticsDialog(object):
    def setupUi(self, OpticsDialog):
        OpticsDialog.setObjectName("OpticsDialog")
        OpticsDialog.resize(640, 480)
        self.widget = QtWidgets.QWidget(OpticsDialog)
        self.widget.setGeometry(QtCore.QRect(200, 90, 191, 231))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SigmaPushButton = QtWidgets.QPushButton(self.widget)
        self.SigmaPushButton.setObjectName("SigmaPushButton")
        self.verticalLayout.addWidget(self.SigmaPushButton)
        self.LaserPushButton = QtWidgets.QPushButton(self.widget)
        self.LaserPushButton.setObjectName("LaserPushButton")
        self.verticalLayout.addWidget(self.LaserPushButton)
        self.StagePushButton = QtWidgets.QPushButton(self.widget)
        self.StagePushButton.setObjectName("StagePushButton")
        self.verticalLayout.addWidget(self.StagePushButton)

        self.retranslateUi(OpticsDialog)
        QtCore.QMetaObject.connectSlotsByName(OpticsDialog)

    def retranslateUi(self, OpticsDialog):
        _translate = QtCore.QCoreApplication.translate
        OpticsDialog.setWindowTitle(_translate("OpticsDialog", "Optics Tools"))
        self.SigmaPushButton.setText(_translate("OpticsDialog", "SigmaAnalysis"))
        self.LaserPushButton.setText(_translate("OpticsDialog", "Laser Formula"))
        self.StagePushButton.setText(_translate("OpticsDialog", "Stage Flatness Analysis"))
