# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SigamaResult.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SigamaResultForm(object):
    def setupUi(self, SigamaResultForm):
        SigamaResultForm.setObjectName("SigamaResultForm")
        SigamaResultForm.resize(640, 480)
        self.gridLayout = QtWidgets.QGridLayout(SigamaResultForm)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(SigamaResultForm)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.SingleFouceLabel = QtWidgets.QLabel(self.splitter)
        self.SingleFouceLabel.setObjectName("SingleFouceLabel")
        self.AllFouseLabel = QtWidgets.QLabel(self.splitter)
        self.AllFouseLabel.setObjectName("AllFouseLabel")
        self.BestAFLabel = QtWidgets.QLabel(self.splitter)
        self.BestAFLabel.setObjectName("BestAFLabel")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(SigamaResultForm)
        QtCore.QMetaObject.connectSlotsByName(SigamaResultForm)

    def retranslateUi(self, SigamaResultForm):
        _translate = QtCore.QCoreApplication.translate
        SigamaResultForm.setWindowTitle(_translate("SigamaResultForm", "Form"))
        self.SingleFouceLabel.setText(_translate("SigamaResultForm", "SingleFouceLabel"))
        self.AllFouseLabel.setText(_translate("SigamaResultForm", "AllFouceLabel"))
        self.BestAFLabel.setText(_translate("SigamaResultForm", "BestAFLabel"))
