# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SigmaAnalysisFunction.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SigmaForm(object):
    def setupUi(self, SigmaForm):
        SigmaForm.setObjectName("SigmaForm")
        SigmaForm.resize(640, 480)
        self.widget = QtWidgets.QWidget(SigmaForm)
        self.widget.setGeometry(QtCore.QRect(110, 160, 421, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(SigmaForm)
        QtCore.QMetaObject.connectSlotsByName(SigmaForm)

    def retranslateUi(self, SigmaForm):
        _translate = QtCore.QCoreApplication.translate
        SigmaForm.setWindowTitle(_translate("SigmaForm", "Sigma Analysis"))
        self.pushButton.setText(_translate("SigmaForm", "Open"))
        self.pushButton_2.setText(_translate("SigmaForm", "Analysis"))
