# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StageFlatnessFunction.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StageForm(object):
    def setupUi(self, StageForm):
        StageForm.setObjectName("StageForm")
        StageForm.resize(640, 480)
        self.layoutWidget = QtWidgets.QWidget(StageForm)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 140, 391, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StageOpenPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.StageOpenPushButton.setObjectName("StageOpenPushButton")
        self.horizontalLayout.addWidget(self.StageOpenPushButton)
        self.StagelineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.StagelineEdit.setObjectName("StagelineEdit")
        self.horizontalLayout.addWidget(self.StagelineEdit)
        self.StageAnalysisButton = QtWidgets.QPushButton(self.layoutWidget)
        self.StageAnalysisButton.setObjectName("StageAnalysisButton")
        self.horizontalLayout.addWidget(self.StageAnalysisButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(StageForm)
        QtCore.QMetaObject.connectSlotsByName(StageForm)

    def retranslateUi(self, StageForm):
        _translate = QtCore.QCoreApplication.translate
        StageForm.setWindowTitle(_translate("StageForm", "Stage Flatness Analysis"))
        self.StageOpenPushButton.setText(_translate("StageForm", "Open"))
        self.StageAnalysisButton.setText(_translate("StageForm", "Analysis"))
